trigger: 
- main

stages:
- stage: Build
  jobs:
  - job: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Npm@1
      inputs:
        command: 'install'
    - task: Npm@1
      inputs:
        command: 'custom'
        customCommand: 'run build'
    
    - task: TerraformInstaller@1
      inputs:
        terraformVersion: 'latest'

    - task: TerraformCLI@2
      inputs:
        command: 'init'
        allowTelemetryCollection: true
    - task: TerraformCLI@2
      inputs:
        command: 'validate'
        workingDirectory: '$(System.DefaultWorkingDirectory)/'
        allowTelemetryCollection: true
    
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: 'build'
        ArtifactName: 'drop'
        publishLocation: 'Container'

- stage: Deploy 
  jobs:
  - job: Deploy
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: DownloadBuildArtifacts@1
      inputs:
        buildType: 'current'
        downloadType: 'single'
        artifactName: 'drop'
        downloadPath: '$(System.ArtifactsDirectory)'
    - task: AzureRmWebAppDeployment@4
      inputs:
        ConnectionType: 'AzureRM'
        azureSubscription: 'Free Trial(e608b533-08ac-4ced-95bb-4032d6e55680)'
        appType: 'webAppLinux'
        WebAppName: 'youtubeVedios'
        packageForLinux: '$(System.DefaultWorkingDirectory)/build'
        RuntimeStack: 'NODE|18-lts'